from decouple import config
PRETRAINED_SDXL_MODEL_PATH=config("PRETRAINED_SDXL_MODEL_PATH")
LORA_TRAINING_DATASET_PATH=config("LORA_TRAINING_DATASET_PATH")
PROJECT_DEPLOYMENT_PATH=config("PROJECT_DEPLOYMENT_PATH")

AWS_ACCESS_KEY=config("AWS_ACCESS_KEY")
AWS_SECRET_KEY=config("AWS_SECRET_KEY")
AWS_REGION=config("AWS_REGION")
AWS_BUCKET_NAME=config("AWS_BUCKET_NAME")
AWS_URL=config("AWS_URL")